
server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sbb
    username: root
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update